### ISSUE TITLE
如何在不搭建后台的情况下本地开始测试？

### ISSUE THREAD

**Issue by xiaoluBy** [tkestack/charts#15]
不搭建后台，是否可以在本地直接开始测试？

**Comment by lemonli** [comment]
请问你想具体测试什么？ 测试chart的部署？

**Comment by gdchaochao** [comment]
> 不搭建后台，是否可以在本地直接开始测试？

请问下，你这里指的测试是否是Jmeter Suite的接口压测呢？

**Comment by xiaoluBy** [comment]
> 请问你想具体测试什么？ 测试chart的部署？

具体想测试NewMonkey在我们开发的APP上的覆盖能力，请问不连接服务器，本地可以跑起来吗

**Comment by xiaoluBy** [comment]
> > 请问你想具体测试什么？ 测试chart的部署？
> 
> 具体想测试NewMonkey在我们开发的APP上的覆盖能力，请问不连接服务器，本地可以跑起来吗



> > 不搭建后台，是否可以在本地直接开始测试？
> 
> 请问下，你这里指的测试是否是Jmeter Suite的接口压测呢？

具体想测试NewMonkey在我们开发的APP上的覆盖能力，请问不连接服务器，本地可以跑起来吗

**Comment by futumaster** [comment]
可以跑起来的，但是不提供覆盖率信息。覆盖率信息是要部署服务器的。

**Comment by lemonli** [comment]
@xiaoluBy 请问还有问题吗 没问题的话我就关闭这个issue了
