### ISSUE TITLE
k8s 版本要求

### ISSUE THREAD

**Issue by Pandoraemon** [tkestack/charts#16]
根据博文上的1.16.3 helm install 失败， 报错

manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(DaemonSet.spec): missing required field "selector" in io.k8s.api.apps.v1.DaemonSetSpec

**Comment by lemonli** [comment]
可否提供一下
1.哪个chart
2.helm版本

**Comment by Pandoraemon** [comment]
helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

用的是 k8s-big-data-suite 
是参照https://www.cnblogs.com/tencent-cloud-native/p/13938298.html 这篇博文在minikube上跑的

**Comment by kangtiann** [comment]
selector 字段，在1.16版本+ 时会强制验证，必须有。急的话可以先用 腾讯云 TKE 的 1.14 版本。

我们正在创建 1.16 的集群验证问题，快速的话，今天内就可以解决问题并提交 MR。

**Comment by kangtiann** [comment]
在腾讯云1.16 版本K8s集群未复现问题。

不过稳妥起见，提交了PR , 给 HDFS DataNode DeamonSet 加了 selector 字段。
#18 

可以试用一下看看是否可以解决问题，
不能的话，可以 helm install --debug .... 把 debug 打开，看看哪个 DeamonSet 缺少 selector 字段。

在 腾讯云 TKE 1.16 上验证没有复现问题
![image](https://user-images.githubusercontent.com/39302402/103736730-becf3b00-502b-11eb-9937-44e8c57b17c5.png)

![image](https://user-images.githubusercontent.com/39302402/103736769-d8708280-502b-11eb-855b-e0d3a835f726.png)

稳妥起见，修改的部分
![image](https://user-images.githubusercontent.com/39302402/103736883-0fdf2f00-502c-11eb-98da-1c623d789e0b.png)

**Comment by kangtiann** [comment]
@Pandoraemon 已经 Merge 进去 main 分支了，可以用最新的Helm包验证一下。

建议 helm install --debug .... 把 debug 打开，看看具体的报错。
